### ISSUE TITLE
POP3 mail parser isn't same as IMAP mail parser, and POP3 mail parser's implementation is incompleted

### ISSUE THREAD

**Issue by hiroshitoda** [jasonmunro/cypht#144]
I think that POP3 mail data structure is same as IMAP's one.
But in Cypht, POP3 mail parser isn't same as IMAP's one, and POP3 mail parser's implementation is incompleted.
Because of this, POP3 mail parser cannot parse some mail data which is parsable with IMAP mail parser.

**Comment by hiroshitoda** [comment]
So I make pull request #147 for fix POP3 parser in makeshift.

**Comment by jasonmunro** [comment]
Thank you for working on this! You are correct, POP3 and IMAP use different code paths for E-mail structure. The reason for this is because IMAP provides the BODYSTRUCTURE command that we can use to parse a message without having to download the entire thing. So basically we offload message parsing to the IMAP server itself. The POP3 protocol does not have this functionality, so we have no choice but to parse it ourselves, and as you noticed our implementation is incomplete.

I will test and merge your pull request to improve POP3 parsing this week. Thanks again!

**Comment by jasonmunro** [comment]
Pull request is merged. Thanks again!
