### ISSUE TITLE
Prepend nº new messages to the Windows Title when new email detected

### ISSUE THREAD

**Issue by jchevali** [jasonmunro/cypht#163]
While in Inbox or another email folder with auto-detection, if you could prepend the nº of new messages in square brackets to the Windows Title when new email is detected, that could help the user to spot it when using a multi-tabbed web browser, as it'd be sufficient to look at the browser tab to know when there is new email, without having to switch to it to check.
E.g.,
IMAP-default-INBOX-Page 1
could become
[1] IMAP-default-NBOX-Page 1
when there is one new message.
And it could default to the global Unread count when the page focus isn't on any of the Inbox folders.

**Comment by jasonmunro** [comment]
unread counts have been added to the page title for IMAP message list pages. Thanks for the feedback!

**Comment by jasonmunro** [comment]
unread counts when on an IMAP message list page are great, thanks again for this idea. I'm not going to implement the global unread count at this time, because other pages have specific titles I want to maintain, and I'm concerned it might be confusing. If you are on the combined unread view, The page title will have the total as it always did.
