### ISSUE TITLE
Duplicate INBOX in IMAP folder tree (one all caps + one other)

### ISSUE THREAD

**Issue by jchevali** [jasonmunro/cypht#165]
I'm seeing duplicate Inboxes for some IMAP providers, where the Inbox name as listed by the server isn't all capitals.

E.g., imap.mail.yahoo.com calls their inbox "Inbox" (mixed case), as a result I see INBOX and Inbox in the tree.

Also, mail.net-c.com calls their inbox "inbox" (lower case), as a result I see INBOX and inbox in the tree.

As I hover over these, the URL link list_path is different, though they contain the same messages.

**Comment by jasonmunro** [comment]
Hello!
Thanks for the feedback on this. I'm not seeing this problem, so that's weird. IIRC, the code automatically inserts an all caps INBOX if none is returned, since IMAP servers are required to have at least an inbox folder. Seem likely this code is the culprit, but I can't yet explain why this is not happening to me. Could you tell me what version of PHP you are using? Just want to rule out a version issue.

Thanks!

**Comment by jasonmunro** [comment]
Oh wait, I'm stupid. I do have a yahoo account and it shows the same problem you are seeing, I just never use that account much and never noticed. Working on a fix now. Thanks again!
