### ISSUE TITLE
can't change name of smtp server

### ISSUE THREAD

**Issue by mazhigali** [jasonmunro/cypht#177]
![image](https://cloud.githubusercontent.com/assets/26579521/24162747/8da45850-0e79-11e7-9a02-3ad321850541.png)

**Comment by jasonmunro** [comment]
Hello!
I'm not exactly sure what you mean. There are 2 ways to add SMTP servers to Cypht, by defining a default in the hm3.ini file, and by using the Settings -> Servers page. If you have more than one configured, you can use the dropdown you highlighted to switch between them. SMTP servers each have an associated name (set in the hm3.ini file or servers page respectively). If you could elaborate a bit more on what your issue is I would be happy to help resolve it!

Thanks for the feedback

**Comment by mazhigali** [comment]
the issue is that names in the dropdown are the same --- [email-protected] - [email-protected].
and i can't identify nedeed smtp.
That smtps were created automaticly while adding by this way 
![image](https://cloud.githubusercontent.com/assets/26579521/24166534/9ec9ff58-0e84-11e7-8f51-7b3b83b5cda3.png)
and i can't change their names

**Comment by jasonmunro** [comment]
Oh, you mean it actually shows up as "[email - protected]" ? I thought you did that before posting the info here. that is not Cypht doing that. You are not by chance using CloudFlare are you? I found a post suggesting it's happening in CloudFlare and you can toggle it off somehow.

You can also setup profiles (Settings -> Profiles) assigned to each SMTP server which should at least add the "display name" value from the profile to the dropdown
