### ISSUE TITLE
Dovecot imap-login, TLS handshaking failed: no shared cipher 

### ISSUE THREAD

**Issue by billz** [jasonmunro/cypht#184]
Very nice project, Jason. I'm testing cypht as a front end to the mail server I've been running for awhile now. Cypht and the mail server are on the same host.

Using the same login method and credentials as other clients, the following error is thrown by Dovecot when authenticating via TLS with cypht:

```
dovecot: imap-login: Warning: SSL alert: where=0x4008, ret=552: fatal handshake failure [10.1.1.1]
dovecot: imap-login: Warning: SSL: where=0x2002, ret=-1: error [10.1.1.1]
dovecot: imap-login: Warning: SSL alert: where=0x4008, ret=256: warning close notify [10.1.1.1]
dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=10.1.1.1, lip=10.1.1.16, TLS handshaking: SSL_accept() failed: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
```

Running `openssl ciphers -tls1.2 "aRSA:AES:-kEDH:-ECDH:-SRP:-PSK:-NULL:-EXP:-MD5:-DES"` outputs:

`AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:CAMELLIA256-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:SEED-SHA:CAMELLIA128-SHA:RC4-SHA:DES-CBC3-SHA`

...and testing a remote connection with `openssl s_client -connect [hostname]:993 -tls1_2` returns:

```
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : DHE-RSA-AES256-GCM-SHA384
    [snip]
* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN]
 Dovecot ready.
```

Certs are issued by LetsEncrypt and are up to date. `imap_auth_tls=true` in hm3.ini. Running cypht in debug mode, so glad to provide relevant entries in php-error.log. 

**Version info**

Debian Linux 7.11 (wheezy) with
php 5.6.30-1~dotdeb+7.1 (fpm-fcgi)
lighttpd - 1.4.31
postfix - 2.9.6
dovecot - 2.1.7
OpenSSL - 1.0.1t

**Comment by jasonmunro** [comment]
I did a little searching to see if I could find a quick fix for this, but sadly I'm not that lucky today :) Obviously we have a mismatch between the allowed cipher list in php/openssl and the letsencrypt certificate used by dovecot, but I'm at a loss as to why.

The only thing I can think to do is try to replicate this by setting up a letsencrypt cert for dovecot locally and seeing if I can debug it from there. Any chance I could access your dovecot service instead? I don't even need a valid account since I just need to troubleshoot the handshake. If that might be possible (I totally understand if it isn't) you can send the ip to jason at cypht dot org so it's not in this issue thread. If I don't hear from you I will continue trying to replicate locally.

I'm curious if you allow starttls on port 143, and if so, how Cypht works with that. It's a slightly different code path so it would be interesting to see if that fails as well.

Also, you mentioned you are running in debug mode, anything useful in the PHP log when this happens? I noticed we squelch PHP warnings on line 189 of modules/imap/hm-imap.php (with the "@" character before the function call). Removing that, retrying, and checking the error log might provide an additional clue.

Thanks for the detailed feedback and sorry about the problems!

**Comment by billz** [comment]
Followed up re: Dovecot service via email, thanks. I don't currently support starttls on this host. The service was configured some time ago with TLS and it's been working great since. It shouldn't be difficult to enable it though, so I'll do this in the next day or so.

As for the PHP error log, I grepped Hm_Auth_IMAP and came up empty. Scanning through the log I see Hm_Auth_None entries with Page ID: ajax_imap_unread but no obviously useful imap debug info. I'll try removing the '@' as you suggest from this module and rebuild the config.

**Comment by billz** [comment]
Here's the additional PHP debug output:

```
FastCGI-stderr: PHP message: PHP Warning:  stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure in /usr/local/share/cypht/modules/imap/hm-imap.php on line 189
PHP message: PHP Warning:  stream_socket_client(): Failed to enable crypto in /usr/local/share/cypht/modules/imap/hm-imap.php on line 189
PHP message: PHP Warning:  stream_socket_client(): unable to connect to tls://[hostname]:993 (Unknown error) in /usr/local/share/cypht/modules/imap/hm-imap.php on line 189
```

**Comment by billz** [comment]
Resolved this by amending the list of cipher suites provided by both Postfix and Dovecot.

**Comment by vullick** [comment]
Hi,

I had a similar problem when installing Cypht on my mail server (Debian Stretch, Dovecot, Postfix, Roundcube, Letsencrypt, OpenSSL, ...). When trying to add my personal mail server in Cypht settings, I got the error message 

> "unable to save this server, are the username and password correct ?"

and in the log :

> "TLS handshaking: SSL_accept() fail" [...] "no shared cipher"

I too had to "amend the list of cipher suites" in Dovecot, but I searched a while to find how. 
```
ssl_protocols = !SSLv3
ssl_cipher_list = ALL:!ADH:!LOW:!EXP:!aNULL:+HIGH:+MEDIUM
```
Before I had only :
`ssl_cipher_list = ALL:!ADH:!LOW:!SSLv2:!SSLv3:!EXP:!aNULL:+HIGH:+MEDIUM `

I know this bug is closed, but the problem seems to be still there, so this message can maybe help someone later.

And yet it is solved, and I can test cypht :) thank you
