### ISSUE TITLE
Raspbian install

### ISSUE THREAD

**Issue by mwolfeu** [jasonmunro/cypht#194]
Every step (1-4) works great till I try to create a user:

mysql> show tables;
+---------------------+
| Tables_in_cyphtMail |
+---------------------+
| hm_user             |
| hm_user_session     |
| hm_user_settings    |
+---------------------+

-----------------------------------------------------------------------

php ./scripts/create_account.php testuser testpass
PHP Fatal error:  Call to a member function prepare() on a non-object in /usr/local/share/cypht/lib/auth.php on line 159

I already triple checked  hm3.ini
Using php5 
I installed  php5-mysql with no change.

Thanks,
Michael

**Comment by jasonmunro** [comment]
Thanks for the feedback. Sounds like maybe the PHP PDO driver is missing? I know you said you installed php5-mysql, but there may be another package for the PDO driver. You can test for this easily enough with the following command line:

```
jason [ ~ ]$ php -r 'phpinfo();' | grep 'PDO Driver'
PDO Driver for MySQL => enabled
PDO Driver for PostgreSQL => enabled
PDO Driver for SQLite 3.x => enabled
```

**Comment by jasonmunro** [comment]
I just pushed some changes that improve the output when an error occurs with this script. Should help debug these issues. I'm closing this since it's been a few weeks and I don't think this is a bug in cypht per say (we needed to better handle errors which this change also does).

If this turns out to be a bug please re-open or file a new ticket. Thanks for the feedback!
