### ISSUE TITLE
Cannot save settings when logged with dynamic auth

### ISSUE THREAD

**Issue by hartois** [jasonmunro/cypht#204]
After last commits I cannot save settings if I enable dynamic auth.
I get the following message, although I'm sure that I enter the correct password:
Incorrect password, could not save settings to the server

**Comment by jasonmunro** [comment]
I have been doing a lot of refactoring lately, it's likely I broke this. Thanks for the report, I will dig into it and get it fixed!

**Comment by jasonmunro** [comment]
Fix pushed in https://github.com/jasonmunro/cypht/commit/c9a980c6addc51e9f0a5b9d31b40bc81ee331bf8 When you have a chance to test it out let me know if it works for you, it's working here

**Comment by hartois** [comment]
Yes, now the settings are saved.
Tell me please, why do I need to enter a password to save the settings?

**Comment by jasonmunro** [comment]
Settings saved between logins are encrypted at rest. The encryption key is derived from your Cypht password. Because of this we cannot access a user's settings, or save them, without that password. Because that password is not saved anywhere on the server, you have to re-enter it to save your settings.

**Comment by hartois** [comment]
I understand
