### ISSUE TITLE
[Bug] EMails in<mail@world.org> Format cause Problems

### ISSUE THREAD

**Issue by ulfgebhardt** [jasonmunro/cypht#218]
Hi,

EMails in the Format &lt;peter@world.og> cause Problems.

- In "Sent" Dialog the "Sent-to" where the Address or name shows is empty, inspect reveals its actually empty when EMails are in the "&lt;peter@world.og>" Format. See Exhibit A
- Sometimes when composing new Mails with "&lt;peter@world.og>" in the address will make the EMail not send correctly and not show up under Sent at all < thats particular anoying.
- When sending to those Addresses Attachments fail to transmit quite frequently
- Those Addresses do not match towards the Local Addressbook (could also be a multi-recipient thingy) and apear without a name, just "&lt;peter@world.og>"

- EMails with " "Peter" &lt;peter@world.org>" work correctly

This behaviour often occurs when sending to multiple recipients.

Revision: [5f2d5c5f8e2f9083c84d795b8337ffc403eab42f](https://github.com/jasonmunro/cypht/commit/5f2d5c5f8e2f9083c84d795b8337ffc403eab42f)

A wild guess - which might not be helpful at all - it could be escaping - html uses &lt;> - [htmlentities](http://php.net/manual/en/function.htmlentities.php)

Thanks for your Effort - its great Software - I use it <3

Grüße Ulf

Exhibit A:
![crypht](https://user-images.githubusercontent.com/1238238/29682832-bdfa7ecc-890c-11e7-8c27-162bf8bca3f1.png)

Exhibit B:
![crypht2](https://user-images.githubusercontent.com/1238238/29683169-b24a69c4-890d-11e7-87ee-02ecee060bf9.png)

<3

**Comment by ulfgebhardt** [comment]
EMail with 2 &lt;peter@world.org> Addresses - one in "From" other in "CC"

![crypht3](https://user-images.githubusercontent.com/1238238/29692574-1a2b2e70-8931-11e7-9e89-2d36f9b4b093.png)

Reply ommits the EMail from "From" Field.

![crypht4](https://user-images.githubusercontent.com/1238238/29692576-1c1819fa-8931-11e7-9cd1-9ea546d43642.png)

**Comment by jasonmunro** [comment]
I appreciate the thorough feedback on this! Just to make sure I understand the issue:

- recipient addresses of the form <"address"> are not delivered to (double or single quotes or both)
- when sending to more than one recipient, we silently fail on malformed addresses and only send to the valid ones

from what I recall, the form <"address"> is not a valid format. quotes are allowed in the local name portion of an address, but not the domain part. Not to say I won't try to make it work :) I believe servers should be strict about adhering to protocol standards, but clients should be forgiving with regards to what they accept.

The second problem is a bit trickier to handle. We parse the recipient address fields and try to pull out valid address parts, I'm not sure if we can accurately detect that we found a malformed address, but I will look into the code and see what we can do. 

Thanks again for the feedback!

**Comment by jasonmunro** [comment]
Just pushed an update in b9dd0e697 to deal with at least the first problem (which makes the second issue less important I think). Address line parsing to find recipients now works like this:

- We use a regex to match the following pattern: [one or more non-whitespace]@[one or more non-whitespace]
- we loop through these matches, and trim commas or semi-colons from the start and end if they exist
- if the first character is a single or double quote, we skip it since it's quoted which means it's not an address
- we then trim angle brackets, single, and double quotes from the start and end
- then we check if the remaining part is a valid e-mail address per the spec (rfc 3696)

This is still not bullet proof, but it should be better and I think it will fix your situation.

**Comment by ulfgebhardt** [comment]
To define the Problem more correct:

- I think &lt;"peter@world.org"> delivers properly, but has display problems.
- Double+Single-Quotes fail to deliver silently when in cc - which is actually correct since Single-Quote is a valid Part of an EMail, but since the Origin is Microsoft Office we should address the Issue, as you said, afterall it is quite common Software.

A Test would be:
> <"'peter@world.org'">, <"petra@world.org">, <'"petuna@world.org"'>
as To or CC Value. Note, I have never seen the last Part with  Single+Double-Quote.

Regarding parsing the To or CC Field my approach would be the following:
- explode(',',$field)
- regex [validrecipientchars]@[validdomain+singlequote]
- if first & last char is singlequote -> trim it

But you have better Overview over this.
I will update tonight and will give Feedback.

**Comment by ulfgebhardt** [comment]
Sending works properly now!

Tested the following:
&lt;"peter@world.org">, &lt;'peter@world.org'>, "'peter'" &lt;"'peter@world.org'">, <"'peter@world.org'">

A few issues remain
- Display "To"-Field in "Sent" is still empty on some occasions
- The "To"-Field contains "Peter"@mail.world.org, peter@world.org under "Sent" -> This seems to apply to Addresses in the local Address book

**Comment by jasonmunro** [comment]
Thanks for the follow up. Before I changed the code I tested a few things, specifically trying to send to addresses of the format:

&lt;"address"&gt;
&lt;'address'&gt;

Both failed for different reasons. The double quotes failed because the code removed contents in quotes since that is not supposed to be used for addresses (for the most part). The single quotes failed because having a single quote in the domain part is invalid. I did not have any issues with &lt;address&gt; (no quotes), and I did not try having both since I knew just one type of quote would fail.

What I implemented is not totally unlike your approach, just a bit more generalized. It's only flaw that I know of is " notanaddress@blah.com " someother@address.com. It will try to send to notanaddress@blah.com and the actual address (note it needs to have that space before the first double quote and the address, or more precisely, not have a quote before the first char of the local part of the address in quotes). The change successfully deals with quotes inside the angle brackets, both double and single. Keep in mind it's a 2 step process: 1. find what we think are addresses, and 2. validate them against the rfc.

Step 1 is done here:
https://github.com/jasonmunro/cypht/blob/master/modules/smtp/hm-mime-message.php#L154
Step 2 is done here:
https://github.com/jasonmunro/cypht/blob/master/modules/core/functions.php#L166
 
You are correct that I did not deal with display issues yet, now that I can send addresses with this quoting style I can more easily test and fix that :) Just saw your new reply, glad it's working better. I will update again when I resolve the display issues.

Really appreciate the feedback and testing!

**Comment by jasonmunro** [comment]
also I have not tried to enhance the sending logic such that if one recipient is invalid, you are notified or the sending is halted. I could check that any address found in step 1 that fails in step 2 means we should halt sending and warn the user. Still not sure that's the best way to deal with it, but it might be better than nothing (it might catch obvious typos at least).

**Comment by ulfgebhardt** [comment]
Thanks for the quick update! Really appreciate that.

I try to give the best possible Feedback, so its easier for you to solve the Problem. Its a win-win ;-). You make great Software and deserve good Feedback to enhance it.

Regarding the sending logic:
It is irritating that you can send an EMail which partly fails to deliver but the Message "Message sent" pops up. It would be better to have it say "Failed to send Message(partly)" and keep the Compose open including content.

Another display thing I descried above alrdy, but copied it down so its not lost:

 When inspecting an EMail under "Sent" The "To" and "CC"-Field contain
> "Peter"@mail.world.org, peter@world.org
> &lt;"some@address.com"@mail.world.org>
> This seems to apply to Addresses in the local Address book

This might be an Serverproblem - i cannot tell yet. If you like I can make a seperate Issue for that.

Grüße Ulf

<3

**Comment by jasonmunro** [comment]
Should have some time to fix the display issues around this tomorrow. Still working out how I want to handle the "failed to send to all recipients issue". After I fix the display bugs I think I will close this and open a new issue for that specific problem.

**Comment by ulfgebhardt** [comment]
I somehow still have trouble sending EMail - they do not reach destination on some unknown occasions :(

I think it might be space related:

1. have an Email with "From" Field value

`"Peter Worldcitizen" &lt;peter@world.org>`

2. Press reply
3. EMail does not appear in "To" Field in the newly opened Compose

**Comment by jasonmunro** [comment]
Sorry I have not had time to dig into your issues here, been super busy with work this past week. I have not run into this issue - I'm going to try to reproduce it now.

**Comment by jasonmunro** [comment]
@ulfgebhardt I merged some address parsing code paths that I think will resolve the issue of the E-mail not showing up in the reply fields. I'm unable to reproduce this problem unless I have an invalid format (quotes inside the angle brackets), but this merge should fix that as well.

**Comment by ulfgebhardt** [comment]
Mostly fixed.

Two Things Remain:

Problem 1:
1. "peter@world.org" <peter@world.org> in CC
2. reply all
3. "peter@world.org>" <peter@world.org> in Compose CC (note the trailing >)

Problem 2:
1. Have Email in sent with To: <peter@world.org>,<petra@world.org>
2. Sent does not Display To Value in List

**Comment by ulfgebhardt** [comment]
Clsoing in Favor of #246
