### ISSUE TITLE
[BUG] Text-Form of a HTML-EMail has trouble with links

### ISSUE THREAD

**Issue by ulfgebhardt** [jasonmunro/cypht#222]
Hello,
me again - another thing i just noticed
![crypht7](https://user-images.githubusercontent.com/1238238/29735164-221d3724-89f7-11e7-98a6-3de681463a0c.png)

The Link contains the closing ">" which makes it invalid.
This applies only to the Text-Form of a HTML EMail. In HTML Form it works correctly.

~~The Text-Form seems not to be HTML-Escaped. This could be an security risk, even in Text-Form.
See: [htmlentities](http://php.net/manual/en/function.htmlentities.php)~~

Grüße Ulf

<3

**Comment by jasonmunro** [comment]
Text messages are escaped, it's actually the reason this bug exists :) URLs that have a trailing &gt; accidentally match our url regex because they have already been changed to an entity. We can't do the regex before we escape the content, because the links we insert would be escaped as well. To solve this I made a change that does the following:

- escape the content as before
- insert a space before any html entity
- replace strings that look like URLs (match our regex) with actual links
- remove a single space before any html entity

So far it looks like it's working for me. Let me know how it works for you when you can, and again thanks for the feedback!

**Comment by jasonmunro** [comment]
Found and fixed a bug with this, but I believe it is now working better

**Comment by jasonmunro** [comment]
@ulfgebhardt I would like to close this since I think it's fixed, if you could confirm for me that would be great! Thanks!

**Comment by ulfgebhardt** [comment]
Is fixed, please close!
