### ISSUE TITLE
🕷 Inline Message Delete Button does not compute

### ISSUE THREAD

**Issue by ulfgebhardt** [jasonmunro/cypht#225]
Hi Jason,

Inline-View works fine now!

But the Delete Button inside the EMail-Header does nothing. It popsup a confirmation, but does not delete the EMail.

Also the EMail stays open when deleted(via Button on the top) - but I consider this a nice feature, please dont remove it.

Another thing with inline messages is:

1. Browse to Page 2 in an EMail-Folder
2. Open an EMail
3. Press back on the Browser (Page 1 now)
4. Navigate to Page 2
5. EMail is still open - close button does not work.

Rev: 59ff05f71bcbdbc0c9684e70b04e5ee3aa0c23e0

Grüße Ulf

<3

**Comment by jasonmunro** [comment]
Just pushed a fix for this, let me know if it works for you!

**Comment by ulfgebhardt** [comment]
The second Problem was fixed.

Delete Button Problem remains:

- Click the Delete Link inside the EMail
- Confirm Popup 
- EMail closes
- EMail is ~~not~~ deleted

Rev:  33bee91

Grüße Ulf

<3

**Comment by jasonmunro** [comment]
There are some javascript changes involved in this fix, maybe you need to force a refresh to override the cached version? I just retested and it works for me.

- click delete, confirm in the popup dialog
- message view is immediately removed from the display
- loading bar is active
- message is removed from the list
- "message deleted" notice appears at the top of the page

**Comment by ulfgebhardt** [comment]
renamed site.js and regenerated it - no change

**Comment by jasonmunro** [comment]
Weird. I just retested with Chrome and FIrefox, with Cypht in development and production mode, works for me in all cases. When you rerun the config_gen script, it should create a new unique id that is appended to the site.js file, which should force the browser to re-download the updated javascript. If the browser is not re-downloading the new site.js file, it could result in what you are seeing (control-shift-r will force the browser to redownload everything).

There is a bit of a delay after the message detail is removed from the page while we call the server to delete the message and the list is updated. I have been testing this in the INBOX of an IMAP account, I have not tried a combined page, maybe that is where the problem is. I will check that out  now

**Comment by jasonmunro** [comment]
Yep, that's the problem. works on normal IMAP folder views, but not combined pages. Looking into it now!

**Comment by ulfgebhardt** [comment]
Oh, im sorry i didnt mentioned that im on everything with 5 accounts. I also sent you an EMail with another Problem I have which requires private Info to properly test. If you want i can record you a video for the delete button thing.

**Comment by jasonmunro** [comment]
Just responded to your Email, and pushed a fix for that issue. The problem with the delete link is definitely related to combined views vs an IMAP folder page. I have found the code that is failing, I just need to work up a fix :)

**Comment by ItsEcholot** [comment]
Just stumbled upon the delete issue as well, good to know that a fix is in the works.

**Comment by ulfgebhardt** [comment]
Bug still present in ed4cd35

I think it works properly on mobile tho

Grüße Ulf

<3

**Comment by jasonmunro** [comment]
This should be finally fixed! :)

**Comment by ulfgebhardt** [comment]
<3 ur the best!

**Comment by ulfgebhardt** [comment]
If the checkbox infront of the Mail is selected the delete button does not work - if its unchecked it does.

**Comment by jasonmunro** [comment]
another fix is pushed. The easiest way to handle this was to simply uncheck the checkbox before delete :)

**Comment by ulfgebhardt** [comment]
Confirming fix <3
