### ISSUE TITLE
Archive message

### ISSUE THREAD

**Issue by ovv** [jasonmunro/cypht#228]
Hello,

I would like to request a new feature. There is an easy way to set a trash folder and delete a mail, would it be possible to do the same with an archive folder and add an archive button ?

I like keeping my inbox clean and usually heavily rely on the archive feature for that.

Thanks for this software :1st_place_medal:

**Comment by dumblob** [comment]
May I ask what are all differences between an usual folder and an archive folder (except for the label)? I can't see absolutely no difference, but I must be missing something.

**Comment by jasonmunro** [comment]
@dumblob Good point :) I think the idea is more ease of use. For example, when you have a Trash folder enabled, "deleting" a message is the same thing is moving it to the trash. It should be pretty easy to code up since all the basic functionality is there. Just need to add a dialog to the imap folder management page and a button to the message list controls (that only shows up if an archive folder is set). One issue would be what to do if you select messages from 2 accounts, but only one has an archive folder configured?

**Comment by dumblob** [comment]
> I think the idea is more ease of use.

Well, then I would definitely advocate for making this generic (the trash folder is too specific for a general-purpose email client). E.g. extend settings for individual folders to include option with which one can mimic the trash folder functionality (except for other functionality). I understood, that the only change is in a menu. In that case, I would add/allow edition of the message list controls. One could then add/edit the content of a submenu "Move to" or just add directly another item at a specific position in those controls as you proposed.

But I'll wait for @ovv's answer.

**Comment by ovv** [comment]
I took the habit when I had a mail provider that would automatically delete mail in the archive folder when your quota was reached but I'm don't think any provider does that anymore.

A generic setting would be good too it's indeed for an easier use. At the moment when you want to move a mail you first have to check in which account it is to no move it a different one.

As for accounts without the archive/custom folder present, you could not display the button when at least one email without the option configured is selected.

**Comment by marclaporte** [comment]
Here are some ideas of archive settings from Kolab
![2019-02-10-kolab-archive-settings](https://user-images.githubusercontent.com/1004261/52545513-143e3700-2d86-11e9-96ca-a4cc46f656e3.png)

**Comment by marclaporte** [comment]
I will explain more about the "Original Folder" use case:

Tons of emails come in. There are various server-side filters that move them to the right folders. All good.

Now, I need to review mails. I go through the various folders. When I click "Archive", it should no longer be in that folder (because I dealt with it), but findable if necessary. If all archived emails go to the same folder, I lose the information provided by the server-side filters (i.e.: in which folder this email ended up in)

Thanks!

**Comment by Yamakasi** [comment]
This could be a nice feature but there needs to be checked how Kolab does that as it's a different beast.

Tagging can be helpful too in such cases as I think that archives with lots of folders can have their disadvantages server side or resource heavy when you need to search.

**Comment by yvesdaxmaz** [comment]
I have some idea due to the fact that we have to keep the Original folder where the mail was before we archive It,  I can create an Archive parent mailbox within which I will create sub mailbox with the name of each mailbox where archived mail was before.

**Comment by dumblob** [comment]
I think tagging is the easiest thing to do here without introduction of anything complicated (to implement, learn, use).

But if we really wanted to play with concepts like Archiving etc., then I'd rather generalize it - the easiest would be exactly what @yvesdaxmaz proposed, but optimized under the hood somehow to avoid that much copying. Do you @marclaporte see any reasons why the solution of @yvesdaxmaz wouldn't match requirements? I can't find currently any significant downside.

**Comment by Yamakasi** [comment]
Maybe an auto Archive Folder creation as option when creating a folder "Create Achrive Folder as well"

**Comment by dumblob** [comment]
@Yamakasi sounds also like a good option (not difficult to implement and being really intuitive).

**Comment by marclaporte** [comment]
@dumblob : What @yvesdaxmaz proposes is fine. It is one of the options in the screenshot: https://github.com/jasonmunro/cypht/issues/228#issuecomment-462213209

**Comment by jasonmunro** [comment]
Many thanks to @yvesdaxmaz for coding this up. This is merged and I followed up with a few refactors and additions.
