### ISSUE TITLE
🕷 Sent EMails are saved in Inbox instead of Sent

### ISSUE THREAD

**Issue by ulfgebhardt** [jasonmunro/cypht#248]
If you send an EMail, the sent EMail is saved in the Inbox, even tho the Account has the Sent folder properly configured.

This results in an empty Folder when selecting Sent from the Menu, one has to browse to the Account's Inbox to find the EMails sent via Cypht.

Steps:
1. Configure Sent folder for Account
2. Send EMail from Account
3. Select Sent and fail to find EMail just sent
4. Select Account's Inbox over Folder Dialog and find the Mail

Rev:  ed4cd35

Grüße Ulf

<3

**Comment by jasonmunro** [comment]
I'm not having this issue. In order for the configured Sent folder to work for a given IMAP server, it must be associated with an SMTP server in a profile. Otherwise we have no idea which IMAP server to save the message to. If you are seeing a copy in your INBOX, you might want to check Settings -> Site and see if you have the "Always BCC sending address" option set. This causes a message to be sent to the sending account which ends up in the INBOX.

**Comment by ulfgebhardt** [comment]
Thanks, that fixed the Issue!
