### ISSUE TITLE
🕷 [Inline View] Moving unchecked EMails does not work

### ISSUE THREAD

**Issue by ulfgebhardt** [jasonmunro/cypht#253]
If you have not checked the box infront of the EMail the Move Operation does nothing:

### Not working:
![movenotworking](https://user-images.githubusercontent.com/1238238/35194254-dbbe7cbe-feb0-11e7-9c2a-859ae2cf408f.png)

### Working fine:
![moveworking](https://user-images.githubusercontent.com/1238238/35194256-de8e73d6-feb0-11e7-958f-12af8edac5e2.png)

### Other Info

This Issue is probably an Inline View specific Issue

Rev: 34d70a0240c10b6b8ab9fedf7c96cf8a0ef0ed53

Grüße Ulf

<3

**Comment by jasonmunro** [comment]
Totally not surprised by this. Inline message viewing is just a big pain in the butt!

**Comment by jasonmunro** [comment]
@ulfgebhardt Pushed a fix for this last night, let me know when you can!

**Comment by ulfgebhardt** [comment]
Not fixed - still a Problem in 087402ea2aff837a0b9ab024d7e9f93bad71f1cb

**Comment by jasonmunro** [comment]
Confirmed that this is still not 100%. It's works sometimes, but not others. It seems that the inline message event overriding is not firing when in all cases for some reason.

**Comment by ulfgebhardt** [comment]
Still a Problem

**Comment by jasonmunro** [comment]
Yep, it's a race condition situation. The inline view is trying to set it's own callback event for the move feature, but sometimes the standard callback assignment happens after the inline message module, causing it to use the wrong flow and not have the right message id to move.

I worked on this friday, and _almost_ got it sorted. Hope to this week. This is the last of the inline message view bugs I think, I'm tracking them here:

https://github.com/jasonmunro/cypht/projects/1

**Comment by jasonmunro** [comment]
I was going to go ahead and close this but I tested it again just in case an IT WAS STILL NOT WORKING!!! At issue here is some weirdness with how the IMAP move/copy dialog works, as well as some callback hell. I now have a fix that works in all cases. Basically I'm not trying to swap callbacks and pass in the message uuid to override the checked messages anymore. Instead I'm just setting a very specific global uuid to move and when the final callback fires to actually move the message checking to see if it's set and using that instead of any other selected checkbox (and then unsetting it). I'm going to go ahead and close this now, feel free to re-open if you are still having issues. Also, I stopped the UI from scrolling to the top when a message is opened while using inline view. That was a pain! :)

I'm planning on adding some end to end tests for message and message list activities - I will include inline message view operations as a part of that effort!

**Comment by ulfgebhardt** [comment]
Confirming fix! TY <3
