### ISSUE TITLE
Menu Items

### ISSUE THREAD

**Issue by bet0x** [jasonmunro/cypht#271]
How i do modify or add menu items?

**Comment by jasonmunro** [comment]
This is where the site module set comes in. You can use it to override other modules, or add your own, including menu items. I don't have time to elaborate just now, but will follow up when I can (and on your other issues). Sorry about that!

**Comment by jasonmunro** [comment]
To add a link to the main menu of Cypht, you will need to modify the site module set in 2 places. First you will assign your module (your custom code) to a page request identifier in the modules/site/setup.php file like so:

```
/* explination of the values:
 * 'ajax_hm_folders   the page request id to execute our module code on
 * 'my_custom_link'   the name of the module to execute, see modules.php
 * true               boolean to control is this should fire when logged in only
 * 'site'             module set the module belongs to
 * 'main_menu_end'    a module associated with this page request to peg ours to
 * 'before'           fire our module before the main_menu_end (supports both before or after)
 */
add_output('ajax_hm_folders', 'my_custom_link', true, 'site', 'main_menu_end', 'before');

```

then you need to create the module in modules/site/modules.php. It will be named with both the module type, and the value from above (my_custom_link), like so:

```
/**
 * @subpackage site/output
 */
class Hm_Output_my_custom_link extends Hm_Output_Module {
    protected function output() {

        $link = '<li><a>FOO</a></li>';
        $this->concat('formatted_folder_list', $link);
    }
}
```

That's it :) modify the $link variable to control what you want to insert into the menu. Make sure the site module set is enabled in your config, if it isn't add it and rerun the config gen script.

**Comment by jasonmunro** [comment]
Nice! actually the folder list is cached, so refreshing the page does not actually refresh it. You need to use the "reload" link at the bottom to cause it to be recreated. You will want to use debug mode for module development - specifically when adding/remove/re-assigning modules because in production mode that is cached when the config gen is run. As you noticed output modules have a built in html_save() method for potentially dangerous output, there is also a trans() method if you care about supporting i18n.

**Comment by bet0x** [comment]
@jasonmunro Yes, i just started and i already saw the trans module, i will be working on some tutorials and stuff for people.
