### ISSUE TITLE
install instructions lack app_data folder

### ISSUE THREAD

**Issue by ehanuise** [jasonmunro/cypht#286]
I noticed this error in the server logs. Apparently, the theme.ini isn't in the open basedire allowed set : 
Wed Sep 26 10:16:51.133036 2018] [php7:warn] [pid 19627] [client XXXXXXXXXXXXXXX:62417] PHP Warning:  is_readable(): open_basedir restriction in effect. File(/var/lib/hm3/app_data/themes.ini) is not within the allowed path(s): 
(/usr/local/share/cypht:/tmp:/dev/urandom:/var/lib/hm3/users:/var/lib/hm3/attachments)
in /usr/local/share/cypht/modules/core/functions.php on line 478,
referer: XXXXXXXXXXXX

I installed according to the instructions, downloaded via the script, and setup in /usr/local/share/ with data in /var/lib/hm3.
There was no /var/lib/hm3/app_data folder.
I manually created it, chowned it to www-data and now no more errors. (yet, it is empty)

**Comment by jasonmunro** [comment]
Just fixed the install instructions, thanks for the feedback! This error is actually a bit misleading. If you try to check if a file is readable, and it's directory path does not exist on the filesystem, AND open basedir restrictions are in effect - you get this weird error.

The themes module allows you to add your own themes and define them in a custom ini file that belongs in the app_data folder. So the code is checking for that file, but throws this warning because the directory was not created. As long as the directory exists, we can check for the presence of the file with no warning which is why it cleared up once you created it.
