### ISSUE TITLE
🕷 [Inline View] Deleting checked EMails does not work

### ISSUE THREAD

**Issue by ulfgebhardt** [jasonmunro/cypht#299]
### [Inline View] Deleting checked EMails does not work

Deleting an EMail with the In-EMail-Header-Delete Button does not work if the EMail is checked.

### Screeny

![image](https://user-images.githubusercontent.com/1238238/47955491-2ba4a180-df99-11e8-8bb9-d20c968fa70c.png)

### Version

2f06317e82f43b7c6c3ea5a1e50ebca641b01eee

### Relates
This relates to several previous issues like
- https://github.com/jasonmunro/cypht/issues/253
- https://github.com/jasonmunro/cypht/issues/225

**Comment by jasonmunro** [comment]
Fix is in the master branch in e0701cf . Let me know if it works for you and I will apply it to the release candidate as well. As always, thanks for the feedback!

(This was a race condition between event handlers BTW. l also added a bit of logic to remove the deleted message from the list on delete rather than waiting for the entire list to update).

**Comment by ulfgebhardt** [comment]
Confirming Fix!

Thanks <3
