### ISSUE TITLE
Installation on a Plesk managed system

### ISSUE THREAD

**Issue by omocinteractive** [jasonmunro/cypht#303]
## 🗣 Suggestion

Here my experiences on a popular Plesk managed system (17.8) under Ubuntu 16.04:
Add some extensions for the PHP cli version:

sudo apt-get install php7.2-mbstring
sudo apt-get install php7.2-curl
sudo apt-get install php7.2-mysql

Add pathes to the open_basedir value:
{:}/usr/local/share/cypht{:}/var/lib/hm3

sudo chmod -R 777 /var/lib/hm3/

It's a good project, but i wish the system will be a part of nextcloud (the mail system in nextcloud is very very rudimental).

Kind regards,
Andreas

**Comment by omocinteractive** [comment]
Feel free to integrate the system into nextcloud - it would be great! I still have to use a external mailsystem because there is no signature and no multiple smtp-server in the offical mailsystem-app - not a good requirement to use it for business.

https://docs.nextcloud.com/server/12/developer_manual/app/startapp.html
- you don't need to add the calendar-feature
- contact, attachment-data comes from nextcloud

**Comment by dumblob** [comment]
I mean, Nextcloud fans shall integrate Cypht into Nextcloud, not the Cypht project itself. It seems Nextcloud dictates strongly how the Nextcloud app shall look like and therefore it might be a viable option to create a fat wrapper over the existing Cypht (and this wrapper most probably won't be part of Cypht because it's too specific and too restrictive and also not easy to test - especially considering the bustling development around Nextcloud, ownCloud and their apps).

**Comment by jasonmunro** [comment]
@omocinteractive thanks for the feedback around Plesk. Having looked briefly at the nextcloud system, it is extremely unlikely that Cypht would be something they want to integrate. Nextcloud has a unified back end system that you create "apps" to work with - Cypht is a complete stand alone program that does not fit that paradigm. With that said, if nextclould exposes features via standard protocols (like carddav), that is something I'm happy to make Cypht work with. In conclusions I'm closing this issue because:

1. nextcloud integration as an "app" appears impossible
2. the valid point from @dumblob that this would need to be done from nextcloud not here
3. there are no actionable items related to this issue.

Thanks again for the feedback!
