### ISSUE TITLE
Choose a community chat strategy, and then promote it massively

### ISSUE THREAD

**Issue by marclaporte** [jasonmunro/cypht#352]
@ulfgebhardt asked a very good question: https://github.com/jasonmunro/cypht/issues/311#issuecomment-507710037

We should:

1- Confirm the community chat strategy

a) https://gitter.im/cypht-org/community is fine.

b) but if we want XMPP (which would permit users to pick own client, and be re-connected), we can do cypht@conference.wikisuite.chat More info at: https://wikisuite.chat/ or self-host cypht@conference.cypht.org

2- Once we have confirmed, let's create a permanent URL http://cypht.org/chat or http://chat.cypht.org/ which redirects to the chosen system. So we can easily change tools if appropriate.

3- Promote this URL everywhere devs will see it, especially at the top of https://github.com/jasonmunro/cypht 

Thoughts?

**Comment by ulfgebhardt** [comment]
Discord is also an valid option for this purpose and by now widely spread. I can certainly assist with making a server for that - if you choose to go for discord

**Comment by streaps** [comment]
I'm not convinced that switching to / adding yet another closed source chat silo (discourse) is the best idea (for an open source project).

An XMPP MUC might be useful for XMPP users, but there are not many. I see much more disadvantages than advantages in comparison to IRC. I prefer IRC and if you like to offer XMPP group chat, there is always Biboumi as an IRC-XMPP bridge.

Freenode recently switched their webchat to KiwiIRC, which is quite nice. Why not put a link to https://webchat.freenode.net/#hastymail on the Contact page?

Btw, is there a reason why the IRC channel is still named #hastymail?

**Comment by marclaporte** [comment]
Would be good to do a redirect / alias / forward from #hastymail to #cypht

**Comment by streaps** [comment]
Just a crazy idea, most likely too much work:

add NNTP support to Cypht, setup a NNTP-server and use a newsgroup as a community forum. It could be even in Slack-style :)

There is also a NNTP based forum: https://github.com/CyberShadow/DFeed
which is used on https://forum.dlang.org/

**Comment by Yamakasi** [comment]
@marclaporte Why would "you" want to change this we "we" ? It's not needed, there is already enough ways to communicate.

Let's stay focused on optimizing Cypht and make it better, more flexible and keep it secure as @jasonmunro his intention was.

As @streaps "just a crazy idea" ;)

**Comment by marclaporte** [comment]
@Yamakasi: To make Cypht "better, more flexible and keep it secure", we need more contributors.

There are currently two chat rooms. I am saying we should settle on one. Ideally, with some level of stickiness (and not have a mailing list). Gitter sends you an email when there are new messages. IRC or XMPP: there are clients.

And I want this chatroom to be one of the first things potential contributors see. Ex.: here: https://packagist.org/packages/jason-munro/cypht

**Comment by Yamakasi** [comment]
> 
> 
> @Yamakasi: To make Cypht "better, more flexible and keep it secure", we need more contributors.
> 
> There are currently two chat rooms. I am saying we should settle on one. Ideally, with some level of stickiness (and not have a mailing list). Gitter sends you an email when there are new messages. IRC or XMPP: there are clients.
> 
> And I want this chatroom to be one of the first things potential contributors see. Ex.: here: https://packagist.org/packages/jason-munro/cypht

Marc, sorry to say, but I think you need to step back a little bit here. You are talking too much "We" as a newcomer that wants to takeover or something it seems.

Users, testers, here know much more about how things are managed in development for Cypht and why this is done like it and how we can rely on @jasonmunro his code(skills) when others have debugged issues, thought of new (small) widely usable features and they are there in no-time.

Looking at your project I know you "want it all" and I also know it's undo able and you might need to create your own fork or stick with what you have.

Cypht is no a Christmastree, it's proper well thought development which you can use/implement or whatever you want.

**Comment by marclaporte** [comment]
@Yamakasi 

I have been managing Free/Libre/Open Source projects for a long long time. When people want to get involved more, my strategy is to encourage them. Wikis and Open Source are about collaboration, and discovering/developing better solutions together.

In the Cypht community, we have two chat room. 

So I turn back the question: What do **you** propose?  Do you think we should leave as is or make a change?

Best regards,

**Comment by Yamakasi** [comment]
> 
> 
> @Yamakasi
> 
> I have been managing Free/Libre/Open Source projects for a long long time. When people want to get involved more, my strategy is to encourage them. Wikis and Open Source are about collaboration, and discovering/developing better solutions together.
> 
> In the Cypht community, we have two chat room.
> 
> So I turn back the question: What do **you** propose? Do you think we should leave as is or make a change?
> 
> Best regards,

Marc,

You are really trying push the Cypth project into a direction that seems to suit you. Cypth doesn't care about what you have managed and what you think about collaboration, Cypth is not the target for large adopt at the moment in a short time as people, like you, want to move things into a direction that will change a lot to the current usage/expectations/situation in total, this after @jasonmunro did a lot of optimization last 2 years where there is a good solid product for now that needs some extra features to try out and see how the core for Cypth can handle that.

Why do I say this ? @jasonmunro overthinks a lot about how and why things are done, I develop myself the same way and that gives a product the quality you want. Try to hype it when you cannot deliver makes a project even worse.

Glitter was a test I understood to see if it's workable and because of all the Gitter/Glitter/Slack/Smuck hypes it doesn't make a project better. The biggest channels I know on Slack for an example are even more dead with more people on Slack then they had on IRC. That plus you get a lot of "solutionseekers" that cannot add or be driven by "your community idea" as Cypth is not developed like it, and I'm sure it never will.

Your idea about "making rumour" with lots of documentation, community people floating around everywhere is not going to work for Cypth, neither is that for any good software. I understand your Wiki way of life as you need to run behind every change in every integrated software you have so you need a lot of eyes to make sure you don't run into bugs or don't miss any features.

In my opinion, Cypth is not and never will be like that. You can integrate it, run it seperate and the small optimizations for integrations are nice. @jasonmunro did a great API integration because I have discussed that widely with him for a large hugecase where I'm even behind on my schedule because I want stuff to be clear as it's thought about in Cypth as well. As Cypth is just a tiny but very worthfull piece in it because of the philosophy it makes it even pretty huge in my integration where I can rely on. I know what I can expect and not a project that hops from idea over to idea where it's missing it's target and start to produce garbage because the main dev want to please everyone because otherwise he feels bad.

I think Github is a great solution for Q/A and whatever we need. It's great for @jasonmunro to pickup his things when he can with his busy schedule and we he reports somewhere he will be only be on Gitter from now on I think it's a good thing to follow. He can even make a schedule here when we ask for things and he! We can even do PR's ourself!

For now, keep it this way. We always have email (with a perfectly fine client it seems).

**Comment by marclaporte** [comment]
@Yamakasi: I agree Cypht is great which is why I am getting involved.

If Jason has any feedback (positive or negative) about my contributions, he can speak for himself and share that with me, in public or private.

Now, I think it's time to get opinions of other people on this issue.

**Comment by dumblob** [comment]
Well, I am personally afraid I can't see any strong enough reason to change the current state of things when it comes to communication channels (GitHub as the central point for everything from questions through any discussions up to issues/bugs/pull_requests/etc., packagist.org as the "announcement" channel thanks to `composer.json`, then the Gitter chat, and in the "worst" or "secure" case a personal direct email to @jasonmunro). This feels certainly more than enough...

**Comment by Yamakasi** [comment]
> 
> 
> @Yamakasi: I agree Cypht is great which is why I am getting involved.
> 
> If Jason has any feedback (positive or negative) about my contributions, he can speak for himself and share that with me, in public or private.
> 
> Now, I think it's time to get opinions of other people on this issue.

Marc, it is my personal opinion so what are you talking about ? I discuss such things as often as I/we can with Jason, so not worries about it.

Also your statement "you are getting involved" is pretty wrong stated and frightens people, just PR if you think have something good or report a bug/feature instead of trying to get a hold on everything.

Thanks!

**Comment by jasonmunro** [comment]
I'm not good at marketing things, and I don't put a lot of effort into promotion. However to my mind the OP is accurately articulating a strategy to increase engagement in Cypht that is a good idea. Insofar as what we should do, I agree with @dumblob:

- github is the central location for contributions/questions
- packagist is sort of an announcement channel (also my blog helps here)
- gitter is a nice free modern chat that I periodically login to
- E-mailing me directly is fine (and actually pretty common)

A bigger issue in this discussion that I want to resolve is the concept of "we" - where "we" means the Cypht community. Anyone who writes a comment on an issue, submits a PR, sends me a suggestion in chat or E-mail or just uses Cypht is, if they want to be, part of "we". It is inappropriate for a member of our community to suggest another member is not sufficiently invested in the project to be a part of "we".

@marclaporte and his team have submitted several issues, PRs, and a new website design that I love. They are also exposing Cypht to a new audience and providing a ton of hands on testing. I am very grateful for their contributions.

Ultimately I make the final calls WRT anything that has to do with Cypht. I want those decisions to be informed by the community through respectful and positive discussions based on the merits of the proposal/suggestion not the perceived qualifications of the person making the proposal.

**Comment by Yamakasi** [comment]
@jasonmunro All help is welcome and not being able to support full time a project someone else is promoting doesn't sounds like a good thing to me.

@dumblob underlines in short what I said as well, don't move everything around what is working now. 

Website; it's matter of taste, it doesn't apply to the Cypht design at all so the old one was perfectly fine for me. I hope "we" keep (can) it that way ;)

**Comment by marclaporte** [comment]
I just made our chat room more visible to devs:
https://github.com/jasonmunro/cypht/commit/0562740591fcfcfb4c95bef8c692b2939d7f1ff8

**Comment by marclaporte** [comment]
The current Gitter room at https://gitter.im/cypht-org/community will eventually migrate to Matrix. Here is a status report: https://matrix.org/blog/2021/12/22/the-mega-matrix-holiday-special-2021
