### ISSUE TITLE
Date vs arrival: A little confusing and perhaps a bug when moving messages

### ISSUE THREAD

**Issue by marclaporte** [jasonmunro/cypht#378]
A few things:

![2020-02-23_235650](https://user-images.githubusercontent.com/1004261/75129727-65bb1a80-5698-11ea-9644-e208dce39513.png)

When viewing one message, and in the message list, we can see the sent date, but not the arrival date. I wonder if we should add as an option?
![2020-02-24_000427](https://user-images.githubusercontent.com/1004261/75129899-70c27a80-5699-11ea-98e7-aa7e13620aba.png)

I moved messages from one IMAP account to another (via Cypht): I didn't expect this to change any dates, but the arrival date seems to have changed. On one hand, it makes sense because I did move the emails. But it was not received on the date I moved... This is an edge case... What do you think?

Thanks!

Marc

**Comment by jasonmunro** [comment]
Good point. It is a bit of an edge case, but maybe date makes more sense. I settled on arrival a long time ago over the date header, but I'm not sure the reasoning from 15 years ago still applies.

**Comment by dumblob** [comment]
My preference would be to support either both or at least change `Date` to `Arrival date` :wink:.

**Comment by marclaporte** [comment]
![2020-03-13_140012](https://user-images.githubusercontent.com/1004261/76647571-717d5c80-6533-11ea-83f7-5712208db6d7.png)

**Comment by marclaporte** [comment]
Indicating "arrival date" vs "sent date" is an easy thing to fix, and we'll do it.

My other topic is that when I move the email from one account to another, the data of one of the dates changes. Is this a bug or a feature?

Thanks!

**Comment by Yamakasi** [comment]
This is seriously a legal thing that needs to be overthought a couple of times.

Arrival date can be much earlier when you use mailrelays which are spooling for a a while because some other relay of the IMAP server is not available.

If someone asks for a delivery notice things can go terrible wrong, it's also how you setup your whole mailcluster so I think Date is the most safe one to use.

**Comment by jasonmunro** [comment]
@marclaporte the arrival date is managed by the IMAP server, so moving the message from one account to another resets it. It is not a part of the real E-mail headers per say.

@Yamakasi I think originally, a LONG time ago, I chose arrival date instead of the sent date because it was a performance boost for IMAP servers at the time, and was usually very similar. We should probably switch to the date header.

**Comment by marclaporte** [comment]
@jasonmunro yes, let's please use sent date by default.

**Comment by kroky** [comment]
Please check PR #418 . Marc, the arrival date has been added as part of the extended headers. Not sure we want to spam short headers with one more date field.

**Comment by marclaporte** [comment]
Indeed, short header should how just one date (sent date)

**Comment by marclaporte** [comment]
The default is now "sent date".
