### ISSUE TITLE
When we reply to an email we have sent, it proposes our address

### ISSUE THREAD

**Issue by adrienmaloba** [jasonmunro/cypht#384]
When we have sent an email to a correspondent and we want to reply to the same message.
By clicking on **REPLY**, this suggests us to send a message to the sender, not to the receiver of the sender.
The improvement would be to offer to send an email to the recipient instead of the sender.

![cypht-](https://user-images.githubusercontent.com/28392444/78499929-f2ef9580-7753-11ea-83b9-dabf79f8d647.gif)

**Comment by dumblob** [comment]
I'll second this request with a minor modification - I'd actually expect to have all `To:` `From:` `Cc:` copied with `To:` and `From:` swapped.

**Comment by marclaporte** [comment]
Also, when forwarding a message, the "to" and "cc" are missing.

Open question: should bcc be in the forward? Roundcube doesn't do it. I can think of arguments on both sides. I guess we can see what all the main webmail software and services do...

Current forward message:

----- begin forwarded message -----

From:
Date:
Subject:

**Comment by dumblob** [comment]
>Open question: should bcc be in the forward?

Hm, bcc gets separated from the email before sending and because "saving to sent folder" is usually implemented as sending as well, one would think it'll always be empty in the saved email. On the other hand, I had many times the problem I wanted to find out who was in bcc (I use it quite frequently) and couldn't find anything because it won't get saved.

That said I'd strongly prefer if bcc actually **got saved** alongside with the whole email (and then when replying to it copied to the `bcc` field without any swapping with `to` nor `cc`).

**Comment by marclaporte** [comment]
@dumblob For reply and reply-to-all, I just tested and it looks good to me. Can you confirm?

As for forward: Maybe we should track in a different issue because there are other concerns.
https://github.com/jasonmunro/cypht/pull/558
https://gitter.im/cypht-org/community?at=60d49d5b8c12474d8ccde4c3

**Comment by dumblob** [comment]
Yeah, the mention of swapping shall not be there - I might have been misled by the screenshot - I apologize for the fuss. To clarify, the following is what I actually expect.

Original (in any folder but **sent by me**):
```email
From: a@b.c
To: b@c.d, c@d.e
Cc: d@e.f, e@f.g
```
After I (`a@b.c`) clicked "reply to all":
```email
From: a@b.c
To: b@c.d, c@d.e
Cc: d@e.f, e@f.g
```
(i.e. 1:1 copy)

Note, this shall work even if I have multiple email addresses in Cypht - so the check "whether it originates from me or someone else" shall be performed against every email I have configured Cypht to actively use.
