### ISSUE TITLE
New User Experience (NUX) module should also set special folders

### ISSUE THREAD

**Issue by marclaporte** [jasonmunro/cypht#397]
We have special folder support (Sent, Trash): https://github.com/jasonmunro/cypht/issues/128

And we have the "New User Experience" (NUX) module:
https://github.com/jasonmunro/cypht/tree/master/modules/nux
https://github.com/jasonmunro/cypht/blob/master/modules/nux/services.php

Most (all?) providers have a predictable name for special folders. Let's use that. And create the folder if it doesn't exists yet (which the ISP's webmail will do if we use it first)

This is somewhat related to https://github.com/jasonmunro/cypht/issues/380 in the sense that Cypht should warn about actions that will fail. A missing special folder leads to weirdness.

Thanks!

**Comment by dumblob** [comment]
>And create the folder if it doesn't exists yet (which the ISP's webmail will do if we use it first)

In that case we should have a really good fallback if the guess was wrong. Suggestions?

**Comment by jasonmunro** [comment]
Guessing is going to be a bit hard I think. Localization throws an immediate obstacle into the mix. One option is to start with the more limited but fool proof method: Ask the IMAP server. Some IMAP servers support exposing "special" folders (sent/trash/drafts) via the protocol (pretty sure Gmail does) so that might be good place to start. Cypht has methods for this already in the IMAP lib.

**Comment by marclaporte** [comment]
And for Spam folder as well: https://github.com/jasonmunro/cypht/issues/412

**Comment by marclaporte** [comment]
Related: https://github.com/roundcube/roundcubemail/issues/3565
