### ISSUE TITLE
HTML and MIME view totally broken when only using POP3

### ISSUE THREAD

**Issue by fluffytux** [jasonmunro/cypht#419]
Problems:

Primary issue:
1) When only a POP3 account is configured (for both authentication and back-end server). Only plain text emails display. HTML emails don't display any body, and MIME emails show the base64 encoded text (you can't view or download attachments).

Also:
2) You need to include the imap module for the display to work at all (missing function references showing in the browser console).  Even if you are not using imap.

Steps to reproduce the primary issue:
Undertake a basic/minimalistic install.
Use pop3 account only

If we use IMAP instead, the problem is not there.

Have tested with:

Debian 9, Debian 10 (amd64 bit)
PHP 7, PHP 7.3

Stable version of Cypht, and latest snapshot.

All fail if only using pop3. All work if using IMAP.

Let me know if you need more feedback - the reproduction steps are very simple.

**Comment by jasonmunro** [comment]
@fluffytux thanks for the report. I'm aware that POP3 MIME support is basically non-existent. IMAP parses message structures for us, so we can get the structure of a message then download the selected or default part (this is the IMAP BODYSTRUCTURE command). POP3 has no such feature, so we would have to download the entire message and parse the structure locally to even display a small text part of the message, which is challenging and inefficient to say the least. The module should not fail without IMAP enabled however (your second point) so that part should be relatively easy to fix.

**Comment by marclaporte** [comment]
Proposal: Deprecate POP3 support if no one steps up to maintain it
https://github.com/jasonmunro/cypht/issues/452
